# S02 T05: Exploració de les dades

### Ex1
##### Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un pandas Dataframe. Explora les dades que conté, i queda’t únicament amb les columnes que consideris rellevants.

In [1]:
import numpy as np
import pandas as pd

# flight arrival and departure details for all commercial flights within the USA, from October 1987 to April 2008
df = pd.read_csv('DelayedFlights.csv')
#print(df.shape)
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB
None

In [2]:
df.head(20)

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
5,6,2008,1,3,4,1937.0,1830,2037.0,1940,WN,...,3.0,7.0,0,N,0,10.0,0.0,0.0,0.0,47.0
6,10,2008,1,3,4,706.0,700,916.0,915,WN,...,5.0,19.0,0,N,0,NaN,NaN,NaN,NaN,NaN
7,11,2008,1,3,4,1644.0,1510,1845.0,1725,WN,...,6.0,8.0,0,N,0,8.0,0.0,0.0,0.0,72.0
8,15,2008,1,3,4,1029.0,1020,1021.0,1010,WN,...,6.0,9.0,0,N,0,NaN,NaN,NaN,NaN,NaN
9,16,2008,1,3,4,1452.0,1425,1640.0,1625,WN,...,7.0,8.0,0,N,0,3.0,0.0,0.0,0.0,12.0
10,17,2008,1,3,4,754.0,745,940.0,955,WN,...,5.0,16.0,0,N,0,NaN,NaN,NaN,NaN,NaN
11,18,2008,1,3,4,1323.0,1255,1526.0,1510,WN,...,4.0,9.0,0,N,0,0.0,0.0,0.0,0.0,16.0
12,19,2008,1,3,4,1416.0,1325,1512.0,1435,WN,...,2.0,5.0,0,N,0,12.0,0.0,0.0,0.0,25.0
13,21,2008,1,3,4,1657.0,1625,1754.0,1735,WN,...,5.0,5.0,0,N,0,7.0,0.0,0.0,0.0,12.0
14,22,2008,1,3,4,1900.0,1840,1956.0,1950,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
15,23,2008,1,3,4,1039.0,1030,1133.0,1140,WN,...,2.0,5.0,0,N,0,NaN,NaN,NaN,NaN,NaN
16,25,2008,1,3,4,1520.0,1455,1619.0,1605,WN,...,2.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
17,26,2008,1,3,4,1422.0,1255,1657.0,1610,WN,...,6.0,6.0,0,N,0,40.0,0.0,0.0,0.0,7.0
18,27,2008,1,3,4,1954.0,1925,2239.0,2235,WN,...,3.0,7.0,0,N,0,NaN,NaN,NaN,NaN,NaN
19,30,2008,1,3,4,2107.0,1945,2334.0,2230,WN,...,6.0,7.0,0,N,0,5.0,0.0,0.0,0.0,59.0

In [3]:
df.columns

Index(['Unnamed: 0', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime',
       'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum',
       'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay',
       'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut',
       'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay',
       'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay'],
      dtype='object')

##descriptions: Name Description 
###### 1 Year 1987-2008  
###### 2 Month 1-12   
###### 3 DayofMonth 1-31   
###### 4 DayOfWeek 1 (Monday) - 7 (Sunday)   
###### 5 DepTime actual departure time (local, hhm m)   
###### 6 CRSDepTime scheduled departure time (local, hhmm)   
###### 7 ArrTime actual arrival time (local, hhmm)   
###### 8 CRSArrTime scheduled arrival time (local, hhmm)   
###### 9 UniqueCarrier unique carrier code   
###### 10 FlightNum flight number   
###### 11 TailNum plane tail number   
###### 12 ActualElapsedTime in minutes   
###### 13 CRSElapsedTime in minutes   
###### 14 AirTime in minutes   
###### 15 ArrDelay arrival delay, in minutes   
###### 16 DepDelay departure delay, in minutes   
###### 17 Origin origin IATA airport code   
###### 18 Dest des tination IATA airport code   
###### 19 Distance in miles   
###### 20 TaxiIn taxi in time, in minutes   
###### 21 TaxiOut taxi out time in minutes   
###### 22 Cancelled was the flight cancelled?   
###### 23 CancellationCode reason for cancellation (A = carrier, B = weather, C = NAS, D = security)   
###### 24 Diverted 1 = yes, 0 = no   
###### 25 CarrierDelay in minutes   
###### 26 WeatherDelay in minutes   
###### 27 NASDelay in minutes   
###### 28 SecurityDelay in minutes   
###### 29 LateAircraftDelay in minutes

In [4]:
df['Diverted'].value_counts()

0    1929004
1       7754
Name: Diverted, dtype: int64

In [5]:
df = df.drop(df.columns[0], axis= 1)
cols = ["Year", "Month", 'DayofMonth', 'DayOfWeek', 'FlightNum', 'TailNum','Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay','LateAircraftDelay' ]
dfclean = df.drop(columns = cols)
dfclean.tail(10)

,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,TaxiIn,TaxiOut
1936748,1254.0,1221,1420.0,1359,DL,86.0,98.0,64.0,21.0,33.0,IND,ATL,432,9.0,13.0
1936749,1528.0,1500,1720.0,1642,DL,112.0,102.0,79.0,38.0,28.0,SLC,PHX,507,4.0,29.0
1936750,1531.0,1522,1822.0,1823,DL,111.0,121.0,88.0,-1.0,9.0,MCI,ATL,692,9.0,14.0
1936751,921.0,830,1112.0,1008,DL,111.0,98.0,82.0,64.0,51.0,ATL,PBI,545,8.0,21.0
1936752,1552.0,1520,1735.0,1718,DL,43.0,58.0,27.0,17.0,32.0,HSV,ATL,151,9.0,7.0
1936753,1250.0,1220,1617.0,1552,DL,147.0,152.0,120.0,25.0,30.0,MSP,ATL,906,9.0,18.0
1936754,657.0,600,904.0,749,DL,127.0,109.0,78.0,75.0,57.0,RIC,ATL,481,15.0,34.0
1936755,1007.0,847,1149.0,1010,DL,162.0,143.0,122.0,99.0,80.0,ATL,IAH,689,8.0,32.0
1936756,1251.0,1240,1446.0,1437,DL,115.0,117.0,89.0,9.0,11.0,IAD,ATL,533,13.0,13.0
1936757,1110.0,1103,1413.0,1418,DL,123.0,135.0,104.0,-5.0,7.0,SAT,ATL,874,8.0,11.0

### Ex2
##### Fes un informe complet del data set:.

Resumeix estadísticament les columnes d’interès
Troba quantes dades faltants hi ha per columna
Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...)
Taula de les aerolínies amb més endarreriments acumulats
Quins són els vols més llargs? I els més endarrerits?
Etc.

In [6]:
print(dfclean.describe())

            DepTime    CRSDepTime       ArrTime    CRSArrTime  \
count  1.936758e+06  1.936758e+06  1.929648e+06  1.936758e+06
mean   1.518534e+03  1.467473e+03  1.610141e+03  1.634225e+03
std    4.504853e+02  4.247668e+02  5.481781e+02  4.646347e+02
min    1.000000e+00  0.000000e+00  1.000000e+00  0.000000e+00
25%    1.203000e+03  1.135000e+03  1.316000e+03  1.325000e+03
50%    1.545000e+03  1.510000e+03  1.715000e+03  1.705000e+03
75%    1.900000e+03  1.815000e+03  2.030000e+03  2.014000e+03
max    2.400000e+03  2.359000e+03  2.400000e+03  2.400000e+03

       ActualElapsedTime  CRSElapsedTime       AirTime      ArrDelay  \
count       1.928371e+06    1.936560e+06  1.928371e+06  1.928371e+06
mean        1.333059e+02    1.343027e+02  1.082771e+02  4.219988e+01
std         7.206007e+01    7.134144e+01  6.864261e+01  5.678472e+01
min         1.400000e+01   -2.500000e+01  0.000000e+00 -1.090000e+02
25%         8.000000e+01    8.200000e+01  5.800000e+01  9.000000e+00
50%         1.160000e+02    1.160000e+02  9.000000e+01  2.400000e+01
75%         1.650000e+02    1.650000e+02  1.370000e+02  5.600000e+01
max         1.114000e+03    6.600000e+02  1.091000e+03  2.461000e+03

           DepDelay      Distance        TaxiIn       TaxiOut
count  1.936758e+06  1.936758e+06  1.929648e+06  1.936303e+06
mean   4.318518e+01  7.656862e+02  6.812975e+00  1.823220e+01
std    5.340250e+01  5.744797e+02  5.273595e+00  1.433853e+01
min    6.000000e+00  1.100000e+01  0.000000e+00  0.000000e+00
25%    1.200000e+01  3.380000e+02  4.000000e+00  1.000000e+01
50%    2.400000e+01  6.060000e+02  6.000000e+00  1.400000e+01
75%    5.300000e+01  9.980000e+02  8.000000e+00  2.100000e+01
max    2.467000e+03  4.962000e+03  2.400000e+02  4.220000e+02

In [7]:
print(dfclean.isnull().sum())

DepTime                 0
CRSDepTime              0
ArrTime              7110
CRSArrTime              0
UniqueCarrier           0
ActualElapsedTime    8387
CRSElapsedTime        198
AirTime              8387
ArrDelay             8387
DepDelay                0
Origin                  0
Dest                    0
Distance                0
TaxiIn               7110
TaxiOut               455
dtype: int64

In [8]:
# velocitat mitja miles*hour
dfclean['TempsVol'] = round((dfclean['ArrTime'] - dfclean['DepTime'])/60,2)
# distance /hours
dfclean['velAvgMph'] = round (dfclean['Distance'] / dfclean['TempsVol'],2)
print(dfclean[['Distance', 'TempsVol', 'velAvgMph']].head(20))

    Distance  TempsVol  velAvgMph
0        810      3.47     233.43
1        810      4.13     196.13
2        515      2.93     175.77
3        515      2.17     237.33
4        688      3.02     227.81
5       1591      1.67     952.69
6        828      3.50     236.57
7        828      3.35     247.16
8        162     -0.13   -1246.15
9       1489      3.13     475.72
10      1489      3.10     480.32
11       838      3.38     247.93
12       220      1.60     137.50
13       220      1.62     135.80
14       220      0.93     236.56
15       220      1.57     140.13
16       220      1.65     133.33
17      1093      3.92     278.83
18      1093      4.75     230.11
19       972      3.78     257.14

In [9]:
# bad data
print(dfclean.iloc[8])

DepTime               1029.0
CRSDepTime              1020
ArrTime               1021.0
CRSArrTime              1010
UniqueCarrier             WN
ActualElapsedTime       52.0
CRSElapsedTime          50.0
AirTime                 37.0
ArrDelay                11.0
DepDelay                 9.0
Origin                   IND
Dest                     MDW
Distance                 162
TaxiIn                   6.0
TaxiOut                  9.0
TempsVol               -0.13
velAvgMph           -1246.15
Name: 8, dtype: object

In [18]:
# arriba tard? Bool
# print(dfclean[['ArrDelay', 'DepDelay']].head())
dfclean['DelayMin'] = (dfclean['ArrDelay'] + dfclean['DepDelay']) 
# delaymin > 0
dfclean['Delay'] = dfclean['DelayMin'] > 0
print(dfclean[['Origin','Dest','DelayMin','Delay']].head(10))
# value_count
dfclean['Delay'].value_counts()
print(dfclean['Delay'].value_counts())

delayed = dfclean['Delay'].sum()
total = dfclean.shape[0]
print("Percen vols endarrerits = {} %".format(round((delayed*100)/total, 2)))

  Origin Dest  DelayMin  Delay
0    IAD  TPA      -6.0  False
1    IAD  TPA      21.0   True
2    IND  BWI      22.0   True
3    IND  BWI      68.0   True
4    IND  JAX      36.0   True
5    IND  LAS     124.0   True
6    IND  MCO       7.0   True
7    IND  MCO     174.0   True
8    IND  MDW      20.0   True
9    IND  PHX      42.0   True
True     1876370
False      60388
Name: Delay, dtype: int64
Percen vols endarrerits = 96.88 %

In [48]:
# Taula aerolínies + delays
by_Cia = dfclean.groupby(by='UniqueCarrier')['DelayMin'].mean()
# dfclean_Cia = dfclean.groupby(by=['UniqueCarrier','DelayMin'])
print (by_Cia)
# print(by_Cia[['UniqueCarrier','DelayMin']].head(10))

UniqueCarrier
9E     94.287188
AA     92.957095
AQ     47.279570
AS     74.036657
B6    110.024033
CO     83.630025
DL     78.887846
EV     95.818779
F9     55.611253
FL     86.171821
HA     67.266863
MQ     88.897127
NW     85.175640
OH     99.930948
OO     90.069320
UA     97.688242
US     75.205067
WN     64.676455
XE    100.144221
YV    110.639563
Name: DelayMin, dtype: float64

In [21]:
# Vols més llargs 
Most_longest_flies = dfclean.sort_values(by='TempsVol', ascending=False)
print(Most_longest_flies[['Origin','Dest','TempsVol','DelayMin']].head(10))

        Origin Dest  TempsVol  DelayMin
1765176    PHX  LAS     39.95     328.0
1179896    ATL  PFN     39.87     425.0
1656812    ATL  BHM     39.75     205.0
1260284    ATL  BHM     39.62     173.0
1176623    ATL  BHM     39.28     161.0
1793034    ATL  BHM     39.23     196.0
1175566    ATL  BNA     39.18     164.0
1179548    ATL  DHN     39.13     255.0
280274     ATL  HSV     39.13     438.0
726753     ATL  BHM     39.12     163.0

In [20]:
# vols més endarrerits
Most_delayed_flies = dfclean.sort_values(by='DelayMin', ascending=False)
print(Most_delayed_flies[['Origin','Dest','DelayMin','Delay']].head(10))

        Origin Dest  DelayMin  Delay
686014     CLT  MSP    4920.0   True
322516     HNL  MSP    4918.0   True
839306     RSW  DTW    3903.0   True
1009553    LIT  DFW    3417.0   True
1881639    BOS  MSP    3252.0   True
1497823    OMA  MSP    3135.0   True
685437     MOT  MSP    3087.0   True
1214839    SEA  MSP    3028.0   True
521096     BNA  MEM    2980.0   True
545038     LGA  MIA    2891.0   True

### Ex3
##### Exporta el data set net i amb les noves columnes a Excel.

In [14]:
dfclean.to_excel ('DelayedFlightsStudied_v1.xlsx', index=False)

ValueError: This sheet is too large! Your sheet size is: 1936758, 18 Max sheet size is: 1048576, 16384

In [49]:
dfclean.to_csv ('DelayedFlightsStudied_v2.csv', index=False, encoding='utf-8')